In [2]:
import pandas as pd

# Load the Excel file
file_path = 'data.xlsx'
excel_data = pd.ExcelFile(file_path)

# Load the data from the first sheet
data = pd.read_excel(file_path, sheet_name='Form Responses 1')

# Function to escape single quotes in SQL
def escape_single_quotes(value):
    if isinstance(value, str):
        return value.replace("'", "''")
    return value

# Generate SQL create table statement and insert statements
table_name = "form_responses"

# Create table statement
create_table_sql = f"""
CREATE TABLE {table_name} (
    id_data INT PRIMARY KEY,
    nama VARCHAR(255),
    nim VARCHAR(50),
    jurusan VARCHAR(255),
    status_kemahasiswaan VARCHAR(255),
    pernah_ikut_mbmk VARCHAR(255),
    pernah_mbkm_apapun VARCHAR(255),
    lolos_mbkm VARCHAR(50),
    performa_ipk VARCHAR(255),
    nilai_ipk VARCHAR(10),
    ikut_organisasi VARCHAR(50),
    jumlah_organisasi INT,
    scan_ktp VARCHAR(50),
    upload_sertifikat VARCHAR(50),
    upload_cv VARCHAR(50),
    upload_surat_rekomendasi VARCHAR(50)
);
"""

# Insert statements
insert_statements = ""
for _, row in data.iterrows():
    insert_statements += f"""
    INSERT INTO {table_name} (
        id_data, nama, nim, jurusan, status_kemahasiswaan, pernah_ikut_mbmk, pernah_mbkm_apapun,
        lolos_mbkm, performa_ipk, nilai_ipk, ikut_organisasi, jumlah_organisasi, scan_ktp, 
        upload_sertifikat, upload_cv, upload_surat_rekomendasi
    ) VALUES (
        {row['id_data']}, '{escape_single_quotes(row['nama'])}', '{escape_single_quotes(row['nim'])}', 
        '{escape_single_quotes(row['jurusan'])}', '{escape_single_quotes(row['status_kemahasiswaan'])}', 
        '{escape_single_quotes(row['pernah_ikut_mbmk'])}', '{escape_single_quotes(row['pernah_mbkm_apapun'])}', 
        '{escape_single_quotes(row['lolos_mbkm'])}', '{escape_single_quotes(row['performa_ipk'])}', 
        '{escape_single_quotes(row['nilai_ipk'])}', '{escape_single_quotes(row['ikut_organisasi'])}', 
        {row['jumlah_organisasi']}, '{escape_single_quotes(row['scan_ktp'])}', 
        '{escape_single_quotes(row['upload_sertifikat'])}', '{escape_single_quotes(row['upload_cv'])}', 
        '{escape_single_quotes(row['upload_surat_rekomendasi'])}'
    );
    """

# Combine the create table and insert statements
sql_script = create_table_sql + insert_statements

# Save the SQL script to a file
sql_file_path = 'form_responses.sql'
with open(sql_file_path, 'w') as file:
    file.write(sql_script)

print(f"SQL script has been saved to {sql_file_path}")

SQL script has been saved to form_responses.sql

In [5]:
from faker import Faker
import uuid

fake = Faker()

def generate_dummy_data():
    unique_id = str(uuid.uuid4())
    base_url = "http://example.com"

    data = {
        'nama': fake.name(),
        'nim': fake.random_int(min=10000000, max=99999999),
        'jurusan': fake.random_element(elements=('Computer Science', 'Information Technology', 'Software Engineering')),
        'status_kemahasiswaan': fake.random_element(elements=('Aktif', 'Cuti', 'Lulus')),
        'pernah_ikut_mbmk': fake.random_element(elements=('Belum', 'Sudah')),
        'pernah_mbkm_apapun': fake.random_element(elements=('Belum', 'Sudah')),
        'lolos_mbkm': fake.random_element(elements=('Tidak', 'Lolos')),
        'performa_ipk': str(fake.random.uniform(2.0, 4.0))[:4],
        'nilai_ipk': fake.random_element(elements=('A', 'B', 'C', 'D', 'E')),
        'ikut_organisasi': fake.random_element(elements=('Ya', 'Tidak')),
        'jumlah_organisasi': fake.random_int(min=0, max=5)
    }

    file_params = {
        'scan_ktp': f"{base_url}/{unique_id}_scan_ktp.png",
        'upload_sertifikat': f"{base_url}/{unique_id}_upload_sertifikat.png",
        'upload_cv': f"{base_url}/{unique_id}_upload_cv.png",
        'upload_surat_rekomendasi': f"{base_url}/{unique_id}_upload_surat_rekomendasi.png"
    }

    return data, file_params

def generate_insert_statement(data, file_params):
    unique_id = str(uuid.uuid4())
    
    add_data_query = """
        INSERT INTO mahasiswa (id, nama, nim, jurusan, status_kemahasiswaan, pernah_ikut_mbmk, pernah_mbkm_apapun, lolos_mbkm, performa_ipk, nilai_ipk, ikut_organisasi, jumlah_organisasi, scan_ktp, upload_sertifikat, upload_cv, upload_surat_rekomendasi)
        VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%d', '%s', '%s', '%s', '%s');
    """ % (
        unique_id,
        data['nama'],
        data['nim'],
        data['jurusan'],
        data['status_kemahasiswaan'],
        data['pernah_ikut_mbmk'],
        data['pernah_mbkm_apapun'],
        data['lolos_mbkm'],
        data['performa_ipk'],
        data['nilai_ipk'],
        data['ikut_organisasi'],
        data['jumlah_organisasi'],
        file_params.get('scan_ktp'),
        file_params.get('upload_sertifikat'),
        file_params.get('upload_cv'),
        file_params.get('upload_surat_rekomendasi')
    )

    return add_data_query

def generate_multiple_inserts(n):
    insert_statements = ""
    for _ in range(n):
        data, file_params = generate_dummy_data()
        insert_statement = generate_insert_statement(data, file_params)
        insert_statements += insert_statement + "\n"
    return insert_statements

n = 1000  # Jumlah data yang ingin di-generate
insert_statements = generate_multiple_inserts(n)

sql_file_path = 'insert_mahasiswa.sql'
with open(sql_file_path, 'w') as file:
    file.write(insert_statements)

sql_file_path

'insert_mahasiswa.sql'